image: "quay.io/podman/stable"

before_script:
  - sed -i "s:# runtime = \"runc\":runtime = \"crun\":g" /usr/share/containers/containers.conf
  - sed -i "s:driver = \"overlay\":driver = \"vfs\":g" /etc/containers/storage.conf
  - podman --version

stages:
  - Static analysis
  - Compile

rustfmt:
  stage: Static analysis
  script:
    - curl -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
    - cargo fmt -- --check

compile:
  stage: Compile
  script:
    - podman build --format docker -t rateway:latest .
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ] && [ "$DOCKERHUB_USERNAME" != "" ] && [ "$DOCKERHUB_PASSWORD" != "" ]; then
        podman login docker.io --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD &&
        podman push rateway:latest docker.io/$DOCKERHUB_USERNAME/rateway:latest;
      fi
