[package]
name = "rateway"
version = "0.1.0"
authors = ["Jens Reidel <adrian@travitia.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6"
async-tungstenite = { version = "0.8", features = ["async-std", "async-native-tls"] }
lapin = { version = "1.2", default-features = false }
