[package]
name = "rateway"
version = "0.1.0"
authors = ["Jens Reidel <adrian@travitia.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
twilight-gateway = { branch = "trunk", default-features = false, features = [
    "rustls",
    "simd-json",
], git = "https://github.com/twilight-rs/twilight" }
twilight-model = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
twilight-http = { branch = "trunk", default-features = false, features = [
    "rustls",
    "simd-json"
], git = "https://github.com/twilight-rs/twilight" }
twilight-cache-inmemory = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
tokio-amqp = { version = "0.1", default-features = false }
lapin = { version = "1.2", default-features = false }
futures = "0.3"
tokio = { version = "0.2", features = ["macros", "rt-core", "rt-threaded"] }
serde = { version = "1", features = ["derive", "rc"] }
structopt = "0.3"
toml = "0.5"
simd-json = { default-features = false, features = [
    "serde_impl",
    "swar-number-parsing"
], version = "0.3" }
env_logger = "0.7"
log = "0.4"
