[package]
name = "rateway"
version = "0.2.0"
authors = ["Jens Reidel <adrian@travitia.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
twilight-gateway = { version = "0.2", default-features = false, features = [
    "rustls",
    "simd-json",
    "simd-zlib",
] }
twilight-model = "0.2"
twilight-http = { version = "0.2", default-features = false, features = [
    "rustls",
    "simd-json"
] }
twilight-cache-inmemory = "0.2"
tokio-amqp = { version = "0.1", default-features = false }
lapin = { version = "1.6", default-features = false }
tokio = { version = "0.2", features = ["macros", "rt-threaded", "stream"] }
serde = { version = "1", features = ["derive", "rc"] }
structopt = { version = "0.3", default-features = false }
toml = "0.5"
simd-json = { default-features = false, features = [
    "serde_impl",
    "swar-number-parsing"
], version = "0.3" }
env_logger = "0.8"
log = "0.4"

[profile.release]
lto = "thin"
