[package]
name = "rateway"
version = "0.1.0"
authors = ["Jens Reidel <adrian@travitia.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
twilight-gateway = { branch = "trunk", default-features = false, features = [
    "rustls",
    "simd-json",
    "simd-zlib"
], git = "https://github.com/twilight-rs/twilight" }
twilight-model = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
futures = "0.3"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
